# Generated by Django 5.1.3 on 2024-11-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(max_length=20)),
                ('device_brand', models.CharField(max_length=20)),
                ('device_browser', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('referal_url', models.URLField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('page_type', models.CharField(max_length=50)),
                ('page_value', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=20)),
                ('event_value', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='analytics.session')),
            ],
        ),
    ]
